# https://github.com/10up/action-wordpress-plugin-asset-update

name: 'Plugin asset/readme update'
description: 'Deploy readme and asset updates to the WordPress plugins repository'
runs:
  using: 'composite'
  steps:
    - id: deploy
      run: chmod +x ./.github/workflows/asset-readme-update/deploy.sh && ./.github/workflows/asset-readme-update/deploy.sh
      shell: bash