# https://github.com/10up/action-wordpress-plugin-deploy/

name: 'Deploy to WordPress.org'
description: 'Deploy to the WordPress plugins repository'
outputs:
  zip-path:
    description: 'Path to zip file'
    value: ${{ steps.deploy.outputs.zip-path }}
runs:
  using: 'composite'
  steps:
    - id: deploy
      env:
        INPUT_GENERATE_ZIP: false
        INPUT_DRY_RUN: false
      run: chmod +x ./.github/workflows/new-version-deploy/deploy.sh && ./.github/workflows/new-version-deploy/deploy.sh
      shell: bash