name: Deploy to WordPress.org

on:
  push:
    tags:
      - "*"

env:
  SLUG: woocommerce-parcelas
  ASSETS_DIR: .wordpress-org
  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Step - Deploy to WordPress.org
        uses: ./.github/workflows/new-version-deploy