name: Plugin asset/readme update

on:
  push:
    branches:
      - trunk

env:
  SLUG: woocommerce-parcelas
  ASSETS_DIR: .wordpress-org
  README_NAME: readme.txt
  IGNORE_OTHER_FILES: false
  SKIP_ASSETS: true
  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}

jobs:
  trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Step - Plugin asset/readme update
        uses: ./.github/workflows/asset-readme-update